package main

import (
	"log"
	"net"
	"net/http"
	"os"

	"github.com/xesina/golang-gin-realworld-example-app/db"
	"github.com/xesina/golang-gin-realworld-example-app/handler"
	"github.com/xesina/golang-gin-realworld-example-app/router"
	"github.com/xesina/golang-gin-realworld-example-app/store"

	swaggerFiles "github.com/swaggo/files"                      // swagger embedded files
	ginSwagger "github.com/swaggo/gin-swagger"                  // gin-swagger middleware
	_ "github.com/xesina/golang-gin-realworld-example-app/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Swagger Example API
// @version 1.0
// @description Conduit API
// @title Conduit API

// @host 127.0.0.1:8585
// @BasePath /api

// @schemes http https
// @produce	application/json
// @consumes application/json

// @securityDefinitions.apikey ApiKeyAuth
// @in header
// @name Authorization

// listenAddr is the address the server binds. It defaulted to a hardcoded
// 127.0.0.1:8585, which is wrong twice over inside a container: loopback is
// unreachable from outside it, and a fixed port ignores the one the runtime
// published. PORT and HOST are the conventional names a container runtime sets,
// and ADDR overrides both for anyone who wants a specific address.
func listenAddr() string {
	if addr := os.Getenv("ADDR"); addr != "" {
		return addr
	}
	host := os.Getenv("HOST")
	if host == "" {
		host = "0.0.0.0"
	}
	port := os.Getenv("PORT")
	if port == "" {
		port = "8585"
	}
	return net.JoinHostPort(host, port)
}

func main() {
	r := router.New()

	r.GET("/swagger/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	v1 := r.Group("/api")

	d := db.New()
	db.AutoMigrate(d)

	us := store.NewUserStore(d)
	as := store.NewArticleStore(d)
	h := handler.NewHandler(us, as)
	h.Register(v1)
	addr := listenAddr()
	log.Printf("listening on %s", addr)
	log.Fatal(http.ListenAndServe(addr, router.RemoveTrailingSlash(r)))
}
